version: "3.8"
services:
  front:
    build: .
    volumes:
      - ./front:/usr/src/app:cached
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "cd /usr/src/app && yarn start"
    ports:
      - 3000:3000